# Generated by Django 3.1.6 on 2021-03-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='movement',
            new_name='mov_data',
        ),
    ]
