# Generated by Django 3.1.6 on 2021-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210215_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_clp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
