# Generated by Django 3.1.6 on 2021-03-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210302_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='product',
        ),
    ]
