# Generated by Django 3.1.6 on 2021-03-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.categoryfilter'),
        ),
    ]
