# Generated by Django 3.1.6 on 2021-03-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210310_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryfilter'),
        ),
    ]
