# Generated by Django 3.1.4 on 2021-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ext',
            field=models.CharField(default='', max_length=10),
        ),
    ]
