# Generated by Django 3.1.6 on 2021-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_movement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='mov_data',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada de producto'), ('salida', 'Salida de producto')], max_length=50, null=True, verbose_name='Movimiento'),
        ),
    ]
