# Generated by Django 3.1.4 on 2021-01-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ext',
        ),
    ]
