# Generated by Django 3.1.6 on 2021-03-02 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210302_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
