# Generated by Django 3.1.6 on 2021-03-02 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210302_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
