# Generated by Django 3.1.6 on 2021-03-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210302_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_clp',
        ),
    ]
