# Generated by Django 3.1.6 on 2021-03-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_price_clp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_active',
            field=models.BooleanField(default=False),
        ),
    ]
